remote_theme: minicomp/ed
# About/contact
author:
  name:              Sarah Watson
  url:               https://www.haverford.edu/users/swatson
  email:             swatson@haverford.edu

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme: blue

