remote_theme: minicomp/ed
# About/contact
title: Haver Tales & Bryn Marvels
author:
  name:              Sarah Watson
  url:               https://www.haverford.edu/users/swatson
  email:             swatson@haverford.edu
